name: Build proxemb

on:
  release:
    types: [published]

jobs:
  build-macos-amd64:
    name: Build for MacOS AMD64
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build proxemb for MacOS AMD64
        run: |
          CGO_ENABLED=1 \
          GOOS=darwin \
          GOARCH=amd64 \
          go build -tags=fts5 -ldflags="-s -w" -o proxemb .

      - name: Compress artifact
        run: tar -czvf proxemb-macos-amd64.tar.gz proxemb

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-macos-amd64.tar.gz
          asset_name: proxemb-macos-amd64.tar.gz
          asset_content_type: application/octet-stream

  build-macos-arm64:
    name: Build for MacOS ARM64
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build proxemb for MacOS ARM64
        run: |
          CGO_ENABLED=1 \
          GOOS=darwin \
          GOARCH=arm64 \
          go build -tags=fts5 -ldflags="-s -w" -o proxemb .

      - name: Compress artifact
        run: tar -czvf proxemb-macos-arm64.tar.gz proxemb

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-macos-arm64.tar.gz
          asset_name: proxemb-macos-arm64.tar.gz
          asset_content_type: application/octet-stream

  build-linux-amd64:
    name: Build for Linux AMD64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
          
      - name: Build proxemb for Linux AMD64
        run: |
          CGO_ENABLED=1 \
          GOOS=linux \
          GOARCH=amd64 \
          go build -tags=fts5 -ldflags="-s -w -extldflags '-static'" -o proxemb .

      - name: Compress artifact
        run: tar -czvf proxemb-linux-amd64.tar.gz proxemb

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-linux-amd64.tar.gz
          asset_name: proxemb-linux-amd64.tar.gz
          asset_content_type: application/octet-stream

  build-linux-arm64:
    name: Build for Linux ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build proxemb for Linux ARM64
        run: |
          CGO_ENABLED=1 \
          GOOS=linux \
          GOARCH=arm64 \
          go build -tags=fts5 -ldflags="-s -w -extldflags '-static'" -o proxemb .

      - name: Compress artifact
        run: tar -czvf proxemb-linux-arm64.tar.gz proxemb

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-linux-arm64.tar.gz
          asset_name: proxemb-linux-arm64.tar.gz
          asset_content_type: application/octet-stream

  build-windows-amd64:
    name: Build for Windows AMD64
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build proxemb for Windows AMD64
        run: |
          $env:CGO_ENABLED = "1"; 
          $env:GOOS = "windows"; 
          $env:GOARCH = "amd64"; 
          go build -tags=fts5 -ldflags="-s -w" -o proxemb.exe .

      - name: Compress artifact
        run: Compress-Archive -Path proxemb.exe -DestinationPath proxemb-windows-amd64.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-windows-amd64.zip
          asset_name: proxemb-windows-amd64.zip
          asset_content_type: application/octet-stream

  build-windows-arm64:
    name: Build for Windows ARM64
    runs-on: windows-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build proxemb for Windows ARM64
        run: |
          $env:CGO_ENABLED = "1"; 
          $env:GOOS = "windows"; 
          $env:GOARCH = "arm64"; 
          go build -tags=fts5 -ldflags="-s -w" -o proxemb.exe .

      - name: Compress artifact
        run: Compress-Archive -Path proxemb.exe -DestinationPath proxemb-windows-arm64.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: proxemb-windows-arm64.zip
          asset_name: proxemb-windows-arm64.zip
          asset_content_type: application/octet-stream
